name: Examples
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  FORCE_COLOR: "1"

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: manual
        run: odin run examples/manual -vet -strict-style
      - name: manual debug
        run: odin run examples/manual -vet -strict-style -debug

      - name: allocator
        run: odin run examples/allocator -vet -strict-style
      - name: allocator debug
        run: odin run examples/allocator -vet -strict-style -debug
